/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import proses.koneksi;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junaidi
 */
public class form_masuk extends javax.swing.JFrame {

    /**
     * Creates new form form_masuk
     */
    DefaultTableModel model;
    
    public form_masuk() {
        initComponents();
        tampil();
    }
    koneksi kon = new koneksi();
    int id=0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Nama = new javax.swing.JLabel();
        lbl_Masuk = new javax.swing.JLabel();
        lbl_berat = new javax.swing.JLabel();
        txt_Masuk = new javax.swing.JTextField();
        txt_Nama = new javax.swing.JTextField();
        txt_Berat = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_londrry = new javax.swing.JTable();
        lbl_jenis = new javax.swing.JLabel();
        cmbpket = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        lbl_berat1 = new javax.swing.JLabel();
        lbl_berat2 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_judul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lbl_Nama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_Nama.setText("masukkan nama  :  ");

        lbl_Masuk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_Masuk.setText("masukkan tanggal masuk :  ");

        lbl_berat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_berat.setText("Masukkan berat :");

        txt_Masuk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MasukActionPerformed(evt);
            }
        });

        txt_Nama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NamaActionPerformed(evt);
            }
        });

        txt_Berat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_Berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BeratActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_edit.setText("update");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_tambah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        tbl_londrry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_londrry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Tanggal  Masuk", "Berat", "harga", "jumlah"
            }
        ));
        tbl_londrry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_londrryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_londrry);

        lbl_jenis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_jenis.setText("Paket Londri : ");

        cmbpket.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbpket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Kilat", "Regular", "Express" }));
        cmbpket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpketActionPerformed(evt);
            }
        });

        txt_harga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        lbl_berat1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_berat1.setText("Harga");

        lbl_berat2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_berat2.setText("Kg");

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));

        lbl_judul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_judul.setText("Masukkan Londrian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(lbl_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_judul)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Daftar Londri yang masuk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Masuk)
                    .addComponent(lbl_Nama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_berat)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_Nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Masuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_Berat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_berat2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_jenis)
                    .addComponent(lbl_berat1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbpket, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(102, 102, 102))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_kembali)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbpket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_jenis)
                            .addComponent(btn_tambah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_edit)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_berat1)
                                .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_berat)
                            .addComponent(lbl_berat2))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_kembali)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MasukActionPerformed

    private void txt_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NamaActionPerformed

    private void txt_BeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BeratActionPerformed
    public void finish (){
        txt_Nama.setText("");
        txt_Masuk.setText("");
        txt_Berat.setText("");
        txt_harga.setText("");
        cmbpket.setSelectedItem("Pilih");
    }
    
    public double hitung(){
        float a = Float.parseFloat(txt_Berat.getText().toString());
        int b  = Integer.parseInt(txt_harga.getText().toString());
        double d = a * b;
        return d;
    }

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed

        //kon = (Connection) koneksi.getKoneksi();
        
        try{
          if(txt_Nama.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Isi Dulu Namanya mu");
          }
          else if(txt_Masuk.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Isi Dulu tanggal");
              }
          else if(txt_Berat.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Isi Dulu berat");
          }
//          else if(cmbjenis.getSelectedItem().equals("")){
//              JOptionPane.showMessageDialog(null, "Isi Dulu jenis");
//          }
          else if(cmbpket.getSelectedItem().equals("")){
              JOptionPane.showMessageDialog(null, "Isi Dulu Paket");
          }
          else{ 
       
       //txt_Total.setText(String.valueOf(d));
              
              String sql = "INSERT INTO transaksi (nama,tanggal_masuk, berat, jenis, harga, jumlah) "
                      + "VALUES ('"+txt_Nama.getText()+"','"+txt_Masuk.getText()+
                      "',"+txt_Berat.getText()+",'"+cmbpket.getSelectedItem()+"',"+txt_harga.getText()+","+hitung()+");";
               kon.stat.executeUpdate(sql);
               tampil();
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"gagal boss "+e);
        }
        
       finish(); 
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void cmbpketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpketActionPerformed
        // TODO add your handling code here:
        if(cmbpket.getSelectedItem().equals("pilih paket terlebih dahulu")){
            txt_harga.setText("");
        }
        else{
            try {
                kon.res = kon.stat.executeQuery("SELECT harga FROM jenis WHERE jenis = '"+cmbpket.getSelectedItem()+"' ");
                while(kon.res.next()){
                    txt_harga.setText(kon.res.getString("harga"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gak bisa nampil : "+e);
            }
        }
    }//GEN-LAST:event_cmbpketActionPerformed

    public void tampil(){
        DefaultTableModel model_tbllondri = new DefaultTableModel();
        model_tbllondri.addColumn("ID");
        model_tbllondri.addColumn("Nama");
        model_tbllondri.addColumn("Tanggal Masuk");
        model_tbllondri.addColumn("Berat");
        model_tbllondri.addColumn("jenis londri");
        model_tbllondri.addColumn("harga");
        model_tbllondri.addColumn("Jumlah");
        tbl_londrry.setModel(model_tbllondri);
        try {
            //kon = (Connection) koneksi.getKoneksi();
            kon.res = kon.stat.executeQuery("SELECT * FROM `transaksi`");
            
            while(kon.res.next()){
                model_tbllondri.addRow(new Object[]{
                    kon.res.getString(1),
                    kon.res.getString(2),
                    kon.res.getString(3),
                    kon.res.getString(4),
                    kon.res.getString(5),
                    kon.res.getString(6),
                    kon.res.getString(7)
                });
                tbl_londrry.setModel(model_tbllondri);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan Error : "+e);
        }
    
    
    }
    private void tbl_londrryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_londrryMouseClicked
        // TODO add your handling code here:
        int row = tbl_londrry.getSelectedRow();
        id = Integer.parseInt(tbl_londrry.getModel().getValueAt(row, 0).toString());
        txt_Nama.setText(tbl_londrry.getModel().getValueAt(row, 1).toString());
        txt_Masuk.setText(tbl_londrry.getModel().getValueAt(row, 2).toString());
        txt_Berat.setText(tbl_londrry.getModel().getValueAt(row, 3).toString());
        cmbpket.setSelectedItem(tbl_londrry.getModel().getValueAt(row, 4).toString());
        txt_harga.setText(tbl_londrry.getModel().getValueAt(row, 5).toString());
       
    }//GEN-LAST:event_tbl_londrryMouseClicked

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
                int hapus = JOptionPane.showConfirmDialog(null, "Yakin Hapus Data ?" ,"Hapus", 
                JOptionPane.YES_NO_OPTION);
        
        if(hapus==JOptionPane.YES_OPTION){
            try {
                String delete = "DELETE FROM transaksi WHERE id_transakasi = '"+id+"'";
                kon.stat.executeUpdate(delete);
                tampil();
                JOptionPane.showMessageDialog(this, "Data Terhapus");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal di hapus : "+e);
            }        
        }
        finish();
        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
       //int edit = JOptionPane.showConfirmDialog(null,"yakin hapus data ? ", "hapus", JOptionPane.YES_NO_OPTION);
       //if(edit == JOptionPane.YES_OPTION){
           try {
               String dtedit = "UPDATE `transaksi` SET `nama` = '"+txt_Nama.getText()+"', `tanggal_masuk` = '"+txt_Masuk.getText()+"',"
                       + " `berat` = "+txt_Berat.getText()+",`jenis` = '"+cmbpket.getSelectedItem()+"', `harga` = "+txt_harga.getText()+", `jumlah` = "+hitung()+" "
                       + "WHERE `transaksi`.`id_transakasi` = "+id+";";
               kon.stat.executeUpdate(dtedit);
               JOptionPane.showMessageDialog(null, "Data Berhasil Di Edit");
               tampil();
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Error Edit"+e);
           }
       //}
       finish();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
         Utama in = new Utama();
         in.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cmbpket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Masuk;
    private javax.swing.JLabel lbl_Nama;
    private javax.swing.JLabel lbl_berat;
    private javax.swing.JLabel lbl_berat1;
    private javax.swing.JLabel lbl_berat2;
    private javax.swing.JLabel lbl_jenis;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JTable tbl_londrry;
    private javax.swing.JTextField txt_Berat;
    private javax.swing.JTextField txt_Masuk;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextField txt_harga;
    // End of variables declaration//GEN-END:variables

//    private void tampilkan() throws SQLException {
//         
//    }
}

